name: Publish the Bloom Gui

on:
  push:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Project
        run:
          dotnet build
          --self-contained
          --configuration Release
          -P:RID=linux-x64

      - name: Run Tests
        run:
          dotnet test
          --no-build
          --verbosity normal
          --configuration Release
          -P:RID=linux-x64

      - name: Download publish-appimage
        uses: supplypike/setup-bin@v1
        with:
          uri: https://raw.githubusercontent.com/kuiperzone/Publish-AppImage/main/publish-appimage
          name: publish-appimage
          version: latest

      - name: Download appimagetool
        uses: supplypike/setup-bin@v1
        with:
          uri: https://github.com/AppImage/AppImageKit/releases/latest/download/appimagetool-x86_64.AppImage
          name: appimagetool
          version: latest

      - name: Build x64 AppImage
        run: publish-appimage -y -r linux-x64

      - name: Upload x64 AppImage
        uses: actions/upload-artifact@v2
        with:
          name: x64-Bloom.AppImage
          path: 'AppImages/Gui-x86_64.AppImage'
          retention-days: 14
          
      - name: Build Arm-32 AppImage
        run: publish-appimage -y -r linux-arm

      - name: Upload Arm-32 AppImage
        uses: actions/upload-artifact@v2
        with:
          name: arm64-Bloom.AppImage
          path: 'AppImages/Gui-arm.AppImage'
          retention-days: 14

      - name: Build Arm-64 AppImage
        run: publish-appimage -y -r linux-arm64

      - name: Upload Arm-64 AppImage
        uses: actions/upload-artifact@v2
        with:
          name: arm64-Bloom.AppImage
          path: 'AppImages/Gui-aarch64.AppImage'
          retention-days: 14

  os-x:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Project
        run: >
          dotnet build
          --self-contained
          --configuration Release
          -P:RID=osx-x64


      - name: Run Tests
        run: >
          dotnet test
          --no-build
          --verbosity normal
          --configuration Release
          -P:RID=osx-x64

      - name: Publish Project to App
        run: >
          mkdir Gui.app

          dotnet publish
          --self-contained
          --output Gui.app
          --configuration Release
          -P:RID=osx-x64

      - uses: actions/upload-artifact@v2
        with:
          name: Bloom.app
          path: './Gui.app'
          retention-days: 14
